# Generated by Django 2.2.7 on 2019-11-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flores',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fotografia', models.ImageField(null=True, upload_to='pelis')),
                ('nombre', models.TextField()),
                ('valor', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
