# Generated by Django 2.2.7 on 2019-11-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flores',
            old_name='valor',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='flores',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='flores',
            name='estado',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flores',
            name='fotografia',
            field=models.ImageField(null=True, upload_to='flor'),
        ),
    ]
